version: '3.7'
services:
  dermacare:
    image: dermacare-service:1.0
    environment:
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
    networks:
      - dermacare
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo:latest
    networks:
      - dermacare
    ports:
      - "27017:27017"
networks:
  dermacare:
    external: true
    name: dermacare
